-- App user & DB Creation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "citext";

\c store_db;

CREATE SCHEMA IF NOT EXISTS public;

GRANT ALL ON SCHEMA public TO store_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO store_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO store_user;

-- Test user & DB Creation
CREATE USER user_test WITH PASSWORD 'pass_test';
CREATE DATABASE store_test WITH OWNER user_test;

\c store_test;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "citext";
CREATE SCHEMA IF NOT EXISTS public;
GRANT ALL ON SCHEMA public TO user_test;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO user_test;